version: '3'

tasks:
  run-local:
    desc: Run app (local)
    env:
      SPRING_PROFILES_ACTIVE: dev
    cmds:
      - mvn spring-boot:run

  test:
    desc: Run tests
    env:
      SPRING_PROFILES_ACTIVE: test
    cmds:
      - mvn test
